site_name: Bayes Deep Compression

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
- blog
- mkdocstrings:
    default_handler: python

nav:
  - Home: index.md
  - User Guide: variational/how_to_use.md
  - Examples: variational/examples.md
  - Reference: 
    - Bayessian NN: variational/reference/bayes_nn.md
    - Bayessian Loss: variational/reference/bayes_nn.md
  - Blog: 
    - blog/index.md

repo_url: https://github.com/intsystems/bayes_deep_compression