site_name: Bayes Deep Compression

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
- blog
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          docstring_style: google

nav:
  - Home: index.md
  - User Guide: user_guide/guide.md
  - Examples: variational/examples.md
  - Reference:
    - 'Parameter Distributions':
      - 'Base Parameter Distributions': reference/methods/bayes/base/distribution.md
      - 'Variance Parameter Distributions': reference/methods/bayes/variational/distribution.md
    - 'Bayessian NN':
      - 'Base Bayessian NN': reference/methods/bayes/base/net.md
      - 'Variance Bayessian NN': reference/methods/bayes/variational/net.md
    - 'Network Distributions':
      - 'Base Network Distributions': reference/methods/bayes/base/net_distribution.md
      - 'Variance Network Distributions': reference/methods/bayes/variational/net_distribution.md
    - Methods:
      - Trainer:
        - 'Base Trainer': reference/methods/trainer/base.md
        - 'Variational Trainer': reference/methods/trainer/variational.md
      - 'Pruner':
        - 'Base Pruner': reference/methods/pruner/base.md
    - Bayessian Loss: 
      - Base Bayessian Loss: reference/methods/bayes/base/loss.md
      - Variance Bayessian Loss: reference/methods/bayes/variational/loss.md
  - Blog: 
    - blog/index.md

repo_url: https://github.com/intsystems/bayes_deep_compression