[tool.poetry]
name = "src"
version = "0.1.0"
authors = ["n.mashalov"]
description= "Compression module"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.1"
pandas = "^2.2.3"
torch = "^2.4"
matplotlib = "^3.9.2"
pydantic-settings = "^2.5.2"
torchvision = "^0.19.1"
typer = "^0.12.5"
gradio = "^5.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.6.9"
isort = "^5.13.2"
mkdocs = "^1.6.1"
mkdocstrings-python = "^1.12.2"
mkdocs-material = "^9.5.43"
coverage = "^7.6.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
