[tool.poetry]
packages = [
    { include = "variational_gaussian", from = "src" },
]
package-mode = true
name = "bayess_deep_compression"
version = "0.1.0"
authors = ["Uncle Sam"]
description = "bayess_deep_compression"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.1"
pandas = "^2.2.3"
matplotlib = "^3.9.2"
torch = {version = "^2.4.1+cpu", source = "pytorch_cpu"}
torchvision = {version = "^0.19.1+cpu", source = "pytorch_cpu"}
scikit-learn = "^1.5.2"
tensorboard = "^2.18.0"
tqdm = "^4.66.5"
pyyaml = "^6.0.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
